### PR TITLE
Removing post-create-project-cmd

### PR DESCRIPTION
**Pull request by simonardejr**
Removing post-create-project-cmd to prevent "Script @php application app:rename handling the post-create-project-cmd event returned with error code 1"

### CODE REVIEW

**Comment by nunomaduro** [comment]
Just a question, what happens now if you use `composer create-project laravel-zero/laravel-zero test-name`. What makes the composer post install script not work anymore? Do you know?

**Comment by simonardejr** [comment]
Just tested with `composer create-project laravel-zero/laravel-zero test-name` and the new project was created, and renamed, successfully.

I'm trying to find out what's causing post install script not working.

**Comment by owenvoke** [comment]
I think the post install script is failing because it expects input, but as it's inside a subprocess it doesn't have any.

**Comment by owenvoke** [comment]
I think this is fine to merge and it doesn't have any side effects. This does seem to be resolved in Composer v2 (although it still fails in the installer), so we could always add it back in later?

I guess it may be worth updating [the docs](https://laravel-zero.com/docs/installation) to mention that `php application app:rename` will need to be run after creating a new project...

Any thoughts by anyone? 🙂

**Comment by dbpolito** [comment]
I think removing is better, Composer v2 fixes it only for Mac/Linux, Windows will still have problems, adding this extra step only for composer create-project is fine, for `laravel-zero/installer` something like https://github.com/laravel-zero/installer/pull/8 looks good

**Comment by nunomaduro** [comment]
Ok sounds good.

**Comment by owenvoke** [comment]
Apologies, I forgot to merge this. :facepalm:

So what needs to be done is:
- Add note to docs
- Merge this

Going forward we are planning to deprecate the Laravel Zero installer. So this issue won't apply there, although I will do one final release with the fix in https://github.com/laravel-zero/installer/pull/8 :+1:

**Comment by owenvoke** [comment]
Thanks for this @simonardejr, and apologies for how long it's been waiting to merge. 😬

**Pull request merged**
