### PR TITLE
added required php extension intl for using box

### PR DESCRIPTION
**Pull request by acrossoffwest**
I stuck with building app and I figured out what was a reason of my issue. I didn't have extension intl so it's PR should resolve that.

### CODE REVIEW

**Comment by owenvoke** [comment]
Thanks @acrossoffwest, this is a good point. It's kind of annoying that this was a side-effect of updating Box. However, I'm hoping a Phar will be added for [Box v3.12](https://github.com/box-project/box/releases/tag/3.12.0) so that we can update to that which removes the dependency on the INTL extension.

I'm going to leave this a couple of days, and if a Phar isn't added (meaning we can't update the Box binary), I'll merge.

**Comment by acrossoffwest** [comment]
@owenvoke any news?

**Comment by owenvoke** [comment]
Whoops! I completely forgot about this, sorry.

Looks like the Box binary hasn't been added yet. https://github.com/box-project/box/issues/530

I think it might be better to add this as a warning to the actual build command as this current change would prevent anyone from using any of the framework, whether they want to use the `app:build` command or not.

Basically, adding the following [before this line in the `BuildCommand`](https://github.com/laravel-zero/framework/blob/master/src/Commands/BuildCommand.php#L65) in the framework repo.

```php
if (! extension_loaded('intl')) {
    $this->error('The INTL extension is currently required for producing builds');
    return;
}
```

**Comment by owenvoke** [comment]
Thanks for this @acrossoffwest, sorry I'd forgotten about it again as work has been pretty busy recently. I've now merged a PR to update to Box v3.12.2 which resolves this issue and no longer requires the INTL extension.

**Pull request closed without merging**
